# Left half (peripheral) configuration
CONFIG_INPUT=y
CONFIG_ZMK_EXT_POWER=y
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y
CONFIG_ZMK_POINTING=y

# WS2812 RGB underglow
CONFIG_WS2812_STRIP=y
CONFIG_ZMK_RGB_UNDERGLOW=y

# DYA-STUDIO
CONFIG_ZMK_SETTINGS_RPC=y
CONFIG_ZMK_SPLIT_RELAY_EVENT=y
CONFIG_ZMK_SETTINGS_SAVE_DEBOUNCE=10000
