# This file generates the GitHub Actions matrix.
# The right half is the central and carries ZMK Studio over USB.
---
include:
  - board: nrfmicro_13
    shield: saturn_left
    artifact-name: saturn_left

  - board: nrfmicro_13
    shield: saturn_right
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n
    artifact-name: saturn_right

  - board: nrfmicro_13
    shield: settings_reset
